### ISSUE TITLE
contentEditable에서 한글 입력 후 개행 시 이슈

### ISSUE THREAD

**Issue by ghkd1418** [a-co-ha/client#7]
![화면_기록_2023-02-21_오후_6_48_51_AdobeExpress (1)](https://user-images.githubusercontent.com/74359527/220312011-ffbad4fc-cf5c-4f5e-b63e-0d6429e23490.gif)

입력중인 블럭 마지막 글자가 다음 블럭에 추가된 채로 생성됨

**Comment by tangjinlog** [comment]
엔터 입력시 끝 글자가 한번 더 입력되는 문제

원인 - IME (Input Method Editor) 가 입력을 처리하는 방식 때문
비 영어권 문자( 한글, 한자 )는 영어 알파벳과 달리 문자를 조합해서 쓰기 때문에 시스템은 언제 조합입력이 끝날지 모른다.
때문에 한글 입력시 음절 끝에 줄이 생기는 것.
<img width="88" alt="image" src="https://user-images.githubusercontent.com/96574345/220622307-cb6bf079-dadb-4ef2-b0ba-1c5b7294c328.png">
onKeyDown , onKeyUp 이벤트에 해당 IME 가 적용되는데, OS 와 브라우저에서 두 번 IME composition(새롭게 언어를 조합해서 변환하는 과정)을 처리하기 때문에  엔터 입력시 onKeyDown 이벤트가 두번 실행돼서 3줄이 생기는 것
<img width="134" alt="image" src="https://user-images.githubusercontent.com/96574345/220623639-e30b0008-2613-47b6-a73e-22601cfb427c.png">

해결 - IME composition이 진행중일 때는 event.nativeEvent.isComposing 속성이 true 이다.
그래서 첫 onKeyDown 실행 시 true이고 두번 째 실행시에는 언어 조합을 끝내고 false로 상태가 바뀌기 때문에,
```javascript
if ( event.nativeEvent.isComposing) {
... 실행로직
}
``` 
해주면 해결된다.
